### ISSUE TITLE
API breaking change: "cluster" have been renamed to "collection"

### ISSUE THREAD

**Issue by flozz** [Vanderhoof/PyNuclino#1]
Hello,

When I try to use PyNuclino on a workspace that contains a "folder" (named "collection" in the UI), I encounter the following error:

    Traceback (most recent call last):
      File "./nuclino_export.py", line 20, in <module>
        pprint(workspace.get_children())
      File "./lib/python3.10/site-packages/nuclino/objects.py", line 77, in get_children
        return [self.nuclino.get_item(id_) for id_ in self.child_ids]
      File "./lib/python3.10/site-packages/nuclino/objects.py", line 77, in <listcomp>
        return [self.nuclino.get_item(id_) for id_ in self.child_ids]
      File "./lib/python3.10/site-packages/nuclino/api.py", line 250, in get_item
        return self.get(path)
      File "./lib/python3.10/site-packages/nuclino/api.py", line 101, in get
        return self._process_response(response)
      File "./lib/python3.10/site-packages/nuclino/api.py", line 75, in _process_response
        return self.parse(data)
      File "./lib/python3.10/site-packages/nuclino/api.py", line 89, in parse
        func = get_loader(source['object'])
      File "./lib/python3.10/site-packages/nuclino/objects.py", line 370, in get_loader
        return classes[name]
    KeyError: 'collection'

After looking at the source and at the API doc (using Internet Archive) I found they renamed "cluster" to "collection" in the API:

![image](https://user-images.githubusercontent.com/971438/210329271-88307ea0-7e0c-4fbe-9b2f-9507320b0241.png)

**Comment by Vanderhoof** [comment]
Thanks a lot for the help! I've merged your PR, and will make a release soon : )

**Comment by Vanderhoof** [comment]
Published [0.2.0](https://pypi.org/project/PyNuclino/)

**Comment by flozz** [comment]
Yeah thank you \o/
